/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {DeviceEventEmitter, StyleSheet, Text, View} from 'react-native';
import {startService, ByronPlayer} from '@byron-react-native/dlna-player';

export default class App extends Component {
  state = {
    status: 'starting',
    message: '--',
    uri: '',
  };
  componentDidMount() {
    startService('Testing');
    DeviceEventEmitter.addListener('dlna-player', data => {
      console.log(' >> dlna-player:', data);
      this.setState({status: data.title, uri: data.url});
    });
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆RNByronDLNA example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
        <Text style={styles.instructions}>{this.state.message}</Text>
        {this.state.uri ? (
          <ByronPlayer
            style={{height: 240, width: '100%'}}
            source={{uri: this.state.uri}}
          />
        ) : null}
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
